### ISSUE TITLE
Variable name for controller group does not match Ansible plugin.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/hyperfoil.github.io#2]
Hi,
 The variable for the hyperfoil-controller group needs to be changed to ansible_hostname. So that the hyperfoil_test task https://github.com/Hyperfoil/hyperfoil_test/blob/master/tasks/main.yml#L3 will work.

Running the Ansible test running results in this error.

> fatal: [agent-1]: FAILED! => {"msg": "The task includes an option with
> an undefined variable. The error was:
> 'ansible.vars.hostvars.HostVarsVars object' has no attribute
> 'ansible_hostname'\n\nThe error appears to have been in
> '/home/benchuser/.ansible/roles/hyperfoil.hyperfoil_test/tasks/main.yml
> ': line 1, column 3, but may\nbe elsewhere in the file depending on the
> exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name:
> Set hyperfoil_controller_host\n  ^ here\n"}
>         to retry, use: --limit
> @/home/benchuser/code/jboss_performance/Hyperfoil-test-runner-for-
> 3Scale/ansible-hyperfoil-3scale-run.retry

**Comment by rvansa** [comment]
This is probably outdated/fixed.
