### ISSUE TITLE
hyperfoil website is not mobile device friendly

### ISSUE THREAD

**Issue by kami619** [Hyperfoil/hyperfoil.github.io#31]
hyperfoil website is close to not usable and unable to navigate using the floating menu and it doesn't render properly for certain pages on mobile devices.

it works fine on desktop browsers.

I am new to the hyperfoil tool and wanted to learn while im on the move and this really hampers my learning curve and requires me to sit infront of a laptop/desktop screen to be able to go through the documentation.

**some screen grabs from the Responsive Rendering mode in FF browser:**

**iPhone 13 mini:**
![iPhone_13_mini_view_port](https://user-images.githubusercontent.com/3415105/153597003-d2c71c2b-0efe-4609-8250-32c7a7261c3f.png)
**iPhone 13 Pro**
![iPhone_13_pro_view_port](https://user-images.githubusercontent.com/3415105/153597005-c30b46b0-85fc-436b-a2c8-5af606c3d6b1.png)
**iPad**
![iPad_view_port_missing_floating_side_menu](https://user-images.githubusercontent.com/3415105/153596987-936d0a6a-5736-4326-a691-5818c41ed84a.png)

**Comment by rvansa** [comment]
Thanks for reporting; I don't think I'll have the expertise for developing mobile-friendly website, though. If you can contribute any improvement we'll be grateful!

**Comment by lampajr** [comment]
I know this is a pretty old issue but, with the recent website renewal, it should be more mobile-friendly.
Therefore closing this issue as completed, feel free to re-open if you consider so :pray:
