### ISSUE TITLE
Quickstart indexes are not same on all pages.

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/hyperfoil.github.io#5]
Quickstarter indexes on most quickstart pages starts correctly on 1. so:
`1. First benchmark
2. Steps and statistics
3. Complex workflow
...`
But on some pages (e. g. https://hyperfoil.github.io/quickstart/quickstart5.html) Starts on different number, like:
`6 .First benchmark
7. Steps and statistics
8. Complex workflow`

**Comment by rvansa** [comment]
Thanks, I'll take a look. Weird.

**Comment by rvansa** [comment]
Handled some while ago.
